name: CD/CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Spacy es_core_news_model
      run: python -m spacy download es_core_news_sm
    - name: Test UnitTest
      run: python -m unittest discover -s tests
