name: Build and Deploy

on: 
  schedule:
    - cron: '0 9,14,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Spacy es_core_news_model
      run: python -m spacy download es_core_news_sm
    - name: Run CUBADEBATE_SPACY.py
      run: python CUBADEBATE_SPACY.py
    - name: Commit chages to gh-pages
      run: |
        git config --global user.name "oleksis"
        git config --global user.email "oleksis.fraga@gmail.com"
        git commit -am "Deploy to gh-pages"
        git push -f origin HEAD:gh-pages
