name: Build and Deploy

on: 
  schedule:
    - cron: '0 4,14,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install Requirements
        run: pip install -r requirements.txt
    - name: Run CUBADEBATE_SPACY.py
      shell: bash
      run: |
        python CUBADEBATE_SPACY.py
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
