name: Build and Deploy

on: 
  schedule:
    - cron: '0 4,14,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install Requirements
      run: pip install -r requirements.txt
    - name: Install Spacy es_core_news_model
      run: python -m spacy download es_core_news_sm
    - name: Run CUBADEBATE_SPACY.py
      run: python CUBADEBATE_SPACY.py
    - name: Commit chages
      run: |
        git config --global oleksis.fraga@gmail.com "you@example.com"
        git config --global user.name "oleksis"
        git commit -am "Deploy to gh-pages"
        git push -f origin gh-pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
