name: Reset and Refresh GH-PAGES

on: 
  schedule:
    - cron: '0 9 10 * *'  # Runs every month day 10 UTC-4 like deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Reset Refresh GH-PAGES
      run: |
        git config --global user.name "oleksis"
        git config --global user.email "oleksis.fraga@gmail.com"
        git checkout gh-pages 
        git reset --hard 7d75f8bc
        git rebase master
        git push -f origin HEAD:gh-pages
