name: Execute Notebook and Release Artifacts

on: 
  release:
    types: [created]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install Requirements
        run: pip install -r requirements.txt
    - name: Run CUBADEBATE_SPACY.py
      shell: bash
      run: |
        python CUBADEBATE_SPACY.py
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: cubadebate
        path: .
      env:
        RUNNER: ${{ toJson(runner) }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: comments_tfidf.json wordcloud_cubadebate.html wordcloud_cubadebate.png capitolio.jpg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
