name: Execute Notebook - Release Artifacts - Deploy

on: 
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Spacy es_core_news_model
      run: python -m spacy download es_core_news_sm
    - name: Run CUBADEBATE_SPACY.py
      run: python CUBADEBATE_SPACY.py
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: cubadebate
        path: .
      env:
        RUNNER: ${{ toJson(runner) }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: comments_tfidf.json top_word_post.json wordcloud_cubadebate.png capitolio.jpg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit chages to gh-pages
      run: |
        git config --global user.name "oleksis"
        git config --global user.email "oleksis.fraga@gmail.com"
        git commit -am "Deploy to gh-pages"
        git push -f origin HEAD:gh-pages
