name: Execute Notebook and Release Artifacts

on: 
  release:
    types: [created]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "CUBADEBATE_SPACY.ipynb"
        params: ""
        isReport: False
        poll: True
    - name: Copy WordCloud Imagen
      shell: bash
      run: |
        cp wordcloud_cubadebate.png ${{ RUNNER.temp }}/nb-runner/
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: cubadebate
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: 
        - wordcloud_cubadebate.png
        - capitolio.jpg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
